name: Base

on:
    workflow_call:
      inputs:
        python:
          required: true
          type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python ${{ inputs.python }}
        uses: actions/checkout@v4.2.2
      - name: Install dependencies
        uses: actions/setup-python@v5.3.0
        with:
          python-version: ${{ inputs.python }}
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov pytest-xdist wheel numpy h5py
          git branch
          pip install -e .    
      - name: create local pymodaq folder and setting permissions
        run: |
          sudo mkdir /etc/.pymodaq
          sudo chmod uo+rw /etc/.pymodaq
      - name: Linting with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=docs
      - name: Run tests
        run: pytest --cov -n auto
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4.6.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
